In [4]:
#Que1) Write a Python Program to Add Two Matrices?

A = [[1,2,3],  
     [4,5,6],  
     [7,8,9]]  
  
B = [[10,11,12],  
     [13,14,15],  
     [16,17,18]]  

import numpy as np

#for addition
Add= np.array(A) + np.array(B)
print(Add)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [6]:
#Que2)  Write a Python Program to Multiply Two Matrices?

A = [[1,2,3],  
     [4,5,6],  
     [7,8,9]]  
  
B = [[10,11,12],  
     [13,14,15],  
     [16,17,18]]

#for multiplication 
M = np.dot(A,B)
print(M)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [10]:
#Que3)  Write a Python Program to Transpose a Matrix?

A = [[1,2,3],  
     [4,5,6],  
     [7,8,9]]  

Transpose_A = np.transpose(A)
print(Transpose_A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
#Que4)  Write a Python Program to Sort Words in Alphabetic Order?

a=input("Enter a sentence : ")

L=a.lower()

Words=L.split()

Words.sort()

for i in Words:
    print(i)

Enter a sentence : I AM my favOUrite
am
favourite
i
my


In [36]:
#Que5) Write a Python Program to Remove Punctuation From a String?

Punctuations= '~`!@#$%^&*()-_+=\|]}[{''"":;,.<>/?'

A = input("Enter a sentence : ")

New_A = " "
for i in A :
    if i not in Punctuations: 
        New_A = New_A + i
print("Renewed sentence is : " ,New_A)    

Enter a sentence : Don't touc*h mee, & myy b@@@aag , Is tha>>tt okay !!??
Renewed sentence is :   Don't touch mee  myy baag  Is thatt okay 
